#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PSYCSL3AmDIZTP1D3pqIihKrZ9UIXfg9KmsF"
APP_SECRET: "sT2nwsH6aB/YGCDgpBC/Ip824tQ3WrXVoqND5q/0XTTzl2yL9Cm+qHnwZUpcCp2L5u72uvEXDYw3gE2Ghf4Xf//o8BmusVAzn014vz8uPX5jbyDZqkjePV3Qo2rL5vj7KLXubvIqWbIg8E0l62veVoiiiDtGfP2p6HY4XIbpJ34OnVOy+1w="

#계좌번호 앞 8자리
CANO: "72013484"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1390380896670191829/V3Zaw-TRiRhS8fHxNOBvXoPPagWrCRgfxGExmVy-uloRT7H2LEcIZ0a7utMNT3YezzmW"